name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:
    name: Lint, Build, Test
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: -Dwarnings

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Tests (compile only)
        run: cargo test --no-run

      - name: Provider tests skipped
        run: echo "Live provider tests require API keys and are not run in CI."
